# =========================================================
# ARQUIVO: .streamlit/secrets.toml (CORRIGIDO)
# =========================================================

# 1. CONFIGURAÇÃO DA PLANILHA
spreadsheet_id = "1iFZt1_RxQWbwdwEaEb7mMLEhzIrBuAXs3UHe4QRv6cg"
worksheet_name = "Complementar"

# 2. CREDENCIAIS DO SERVICE ACCOUNT (Seu código, está OK)
[gcp_service_account]
type = "service_account"
project_id = "automacaowhatsapp-475119"
private_key_id = "69571b38780b46a4c8ad59e877a21cef6707c158"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDrlN+adu0gz7AG
uYnV4aeHB/mQXb3pTwj8MIEvHi9bXTJ0Bk/sSNCzfuC6S4Q4juUMVWXpAYN6ZwgE
qjDrcOVz6+FnnKVSsW5MsSAbQVaoS8KNny1Sv9enswLfAiGvwolv/j/wiPBqn59+
0dH+BN0IQ7309AW6nDDAQmH2bSqgwuRzB25Ci5qZdPgqbKd/UOJ5+5Y0f2rkwcth
ulDISpNI1h7nf7EkdvWPi1pBdg6i58CJAHHkWLuZA3IMKKuLTAV2hdW9RT21oAQe
QcXsGN7UghA7k2YsaVFY6GKCDlinRC6EZnTYOMy3/nZgqD/g9TC1jf+2SmoSIvy1
1mb5JIsPAgMBAAECggEAS3mIQ+ALK6JuZlEmGEhx2ECVU4u87tT773QIx1Q33uEW
a3akP3K6rm8dR4IvK8GYH2HywvpRqbL9riTqhFvIn2F4dy4IB1zCFj7/JsxBm6yd
+aqAJk1BJcCj0FfJ/Bnq118RFBqDT92xBzvot6XOPLobTzGo7jbhJY9+/CjQae05
StgMeT17FTZmljCMyh9huphT2RffaDm3prqHEAkSZO2y4456m2rPgczcoUdJP1+P
K1Q7AfDJNsb6lvPPDmJhld+8kNW1xTBlH6y16R0pBlSMeywPl4trhJNdtHBVQScs
qxvJSx3+t/FeRigbgcUab+irsxzS53ZIKn/Ly1+nCQKBgQD58lyl25FZY6sSoRZQ
SQobxDsqewqOyQ+bu/9JibS56IKlcPhxYBpLzxFS20dwoOckrk6idZ0QHM3w1pbR
iDJ2UrPclGrKSUBW9089lvMt2Q5loHAFdmlOBaPuZf6yaut2y3Y4wkzzgCA+hziy
pv7sg1IAIJIySlLLqysl6KdwGQKBgQDxSXL9/Bxb/RTdXcvQ1IbsPSFmlIXOsGsy
XfHr6Hlf12KBA12XZVc1NuqSnIsdiI4e4ebNCN4AiIPWTTAXhV2IYdVen/C2jnfT
b45H4or6mchoGvnjuWhfvpl2X6sKX3rp6l+dTcP7I3gK1AYSgRRcb04p9NnywVfF
TJUGDPQZZwKBgCYKApujXO2Tw5dkOLcjRoyPQsnmS+cLJnr3E5Unhf+9KRTwqn7m
t1nOO762bJrxgfwNIx6Kc8rd92Gt5uogpj1nvMPXOqFqoIYbwU2vP3c8z3ob/rB2
IvSi2x4PG8Ifj5JWyLk+qONuHnolrjVSQP3RxosKafWJZixk8n4keEcRAoGAXI+1
qlNtuagzudwClSEChVvKFWUCk9C/vrmlVb9/2FFy+1UEMVDyDHr9r7KX94NsKdK1
TJCLQZ8dHDfOLCfAQtJtHPi0SgQLWbQg29i/QfV+mNlIZaC5tokSrAN1ROxt5ZBA
j8LGXPA1W8oMbkrQOcmFLbk9Zs/e0NRZEtIjTh8CgYA4vl8lvYHIrkRgCsgY3Mlp
Sm4eXxBtEahpfvzb2eS8C2JCzUBoJQ9U/KeHLfofYDyss99SKvgbMBG7XDdfc0wE
XIBYDcBBMEjZ/+5p7zp/+lyrKNGz4Pht65qk0IwXt+z2ThTzrw26OVuBO4B83TUO
I5FjCLNN3o0szCcL8/0hug==
-----END PRIVATE KEY-----
"""

client_email = "streamlit-app-service@automacaowhatsapp-475119.iam.gserviceaccount.com"
client_id = "105752060200065925017"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app-service%40automacaowhatsapp-475119.iam.gserviceaccount.com"


# 3. SENHA DE ACESSO DO APP (Obrigatório para o seu login funcionar)
# Adicione a senha que você definiu no config.py
SENHA_ACESSO = "csc2026"